name: Ivy-Framework Publish Build (ex PR)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Ivy-Framework
        uses: actions/checkout@v4
        with:
          path: Ivy-Framework

      - name: Check Code Formatting
        run: dotnet format --verify-no-changes
        working-directory: Ivy-Framework

      - name: Checkout Ivy
        uses: actions/checkout@v4
        with:
          repository: Ivy-Interactive/Ivy
          token: ${{ secrets.IVY_FRAMEWORK_TOKEN }}
          path: Ivy

      - name: Replace %IVY_LICENSE_PUBLIC_KEY% with Secret
        run: |
          $filePath = "Ivy-Framework/frontend/src/lib/license.ts"
          if (Test-Path $filePath) {
            $content = Get-Content $filePath -Raw
            $content = $content -replace '%IVY_LICENSE_PUBLIC_KEY%', '${{ secrets.IVY_LICENSE_PUBLIC_KEY }}'
            Set-Content $filePath $content
            Write-Host "Successfully replaced IVY_LICENSE_PUBLIC_KEY in license.ts"
          } else {
            Write-Error "Could not find license.ts at $filePath"
            exit 1
          }
        shell: pwsh

      - name: Ensure Directory.Build.props is available
        run: |
          if (Test-Path "Ivy/Directory.Build.props") {
            New-Item -ItemType Directory -Path "Ivy-Framework/Ivy" -Force
            Copy-Item -Path "Ivy/Directory.Build.props" -Destination "Ivy-Framework/Ivy/Directory.Build.props" -Force
            Write-Host "Directory.Build.props copied successfully"
          } else {
            Write-Host "Warning: Ivy repository not available. Build may fail if Directory.Build.props is required."
          }
        shell: pwsh

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Workload update
        run: dotnet workload update
        working-directory: Ivy-Framework

      - name: Build Solution
        run: dotnet build --configuration Release
        working-directory: Ivy-Framework

      - name: Run Tests
        run: dotnet test --configuration Release --no-build
        working-directory: Ivy-Framework